[package]
name = "abaqus_inp"
version = "0.1.0"
edition = "2024"
authors = ["Fred Jones <fredjones42@proton.me>"]
description = "Abaqus mesh input file (.inp) parser"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fredjones42/abaqus_inp"
readme = "README.md"
keywords = ["abaqus", "mesh", "fem", "parser", "mcnp"]
categories = ["parser-implementations", "science", "simulation"]

[dependencies]

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "bench"
harness = false
